---
title: "Project 1 EDA"
author: "Team 1"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 
```


```{r, echo=T}
#Importing Necessary Libraries
library(ezids)
library(ggplot2)

#Importing each .csv as data frames, grouped by genre
action = read.csv("action.csv")  
adventure = read.csv("adventure.csv")
animation = read.csv("animation.csv")
biography = read.csv("biography.csv")
crime = read.csv("crime.csv")
family = read.csv("family.csv")
fantasy = read.csv("fantasy.csv")
noir = read.csv("film-noir.csv")
history = read.csv("history.csv")
horror = read.csv("horror.csv")
mystery = read.csv("mystery.csv")
romance = read.csv("romance.csv")
scifi = read.csv("scifi.csv")
sports = read.csv("sports.csv")
thriller = read.csv("thriller.csv")
war = read.csv("war.csv")
```

```{r, echo=T}
#Checking structure of the data frames (all should be the same as action)
str(action)
```
```{r, echo=T}
#We can remove some columns as we will not be needing them (some others are left in as we could use possibly ask more questions about them later)
action = subset(action, select = -c(description, director, director_id, star, star_id, gross.in...))

#Showing the new structire of the data frame
str(action)
```
```{r, echo=T}
#Removing the columns for the rest of the data frames
adventure = subset(adventure, select = -c(description, director, director_id, star, star_id, gross.in...))

animation = subset(animation, select = -c(description, director, director_id, star, star_id, gross.in...))

biography = subset(biography, select = -c(description, director, director_id, star, star_id, gross.in...))

crime = subset(crime, select = -c(description, director, director_id, star, star_id, gross.in...))

family = subset(family, select = -c(description, director, director_id, star, star_id, gross.in...))

fantasy = subset(fantasy, select = -c(description, director, director_id, star, star_id, gross.in...))

noir = subset(noir, select = -c(description, director, director_id, star, star_id, gross.in...))

history = subset(history, select = -c(description, director, director_id, star, star_id, gross.in...))

horror = subset(horror, select = -c(description, director, director_id, star, star_id, gross.in...))

mystery = subset(mystery, select = -c(description, director, director_id, star, star_id, gross.in...))

romance = subset(romance, select = -c(description, director, director_id, star, star_id, gross.in...))

scifi = subset(scifi, select = -c(description, director, director_id, star, star_id, gross.in...))

sports = subset(sports, select = -c(description, director, director_id, star, star_id, gross.in...))

thriller = subset(thriller, select = -c(description, director, director_id, star, star_id, gross.in...))

war = subset(war, select = -c(description, director, director_id, star, star_id, gross.in...))
```

```{r, echo=T}
#Combining all the data frames and removing duplicates, we can still use the data frames above for analysis, however.  Both methods are valid depending on our questions and eda.
allmovies = rbind(action, adventure, animation, biography, crime, family, fantasy, noir, history, horror, mystery, romance, scifi, sports, thriller, war)

#Remove duplicates
allmovies <- allmovies[!duplicated(allmovies$movie_id), ]

#Check for duplicates
duplicates = sum(duplicated(allmovies))
duplicates
```

```{r, echo=T}
# ==========================
# Q1: Genre vs Rating
# ==========================

# Step 1) Clean year and filter to 2000-2023 with valid ratings.

# The original "year" column was categorized as character variable and included non-numeric values. These irregular entries caused issues when attempted numeric filtering.

# To address this, we extracted only numeric characters from the "year" column using regular expression and converted the result to an integer variable "year_num".
allmovies$year_num <- as.numeric(allmovies$year)

# Keep only movies with valid rating and release year (2000-2023).
allmovies_q1base <- subset(allmovies,
                           !is.na(rating) &
                           !is.na(year_num) &
                           year_num >= 2000 &
                           year_num <= 2023)
dim(allmovies_q1base)
summary(allmovies_q1base$year_num)
sum(is.na(allmovies$year_num))
```

```{r, echo=T}
# Step 2) Create main genre
# - The original genre column can contain multiple genres.
# - Use only the first genre listed to make the analysis interpretable.
allmovies_q1base$main_genre <- trimws(sub(",.*", "", allmovies_q1base$genre))
table(allmovies_q1base$main_genre)
```

```{r, echo=T}
# Step 3) Remove very small genre group (stability for ANOVA)
counts <- table(allmovies_q1base$main_genre)

# Keep genres with al least 100 movies
keep <- names(counts[counts >= 100])

# Filter
allmovies_q1 <- subset(allmovies_q1base, main_genre %in% keep)
allmovies_q1$main_genre <- as.factor(allmovies_q1$main_genre)

table(allmovies_q1$main_genre)
dim(allmovies_q1)
```

```{r, echo=T}
# Step 4) EDA: Boxplot + descriptive statistics

# Visualization with boxplot.
library(ggplot2)

allmovies_q1 <- allmovies_q1 %>%
  mutate(main_genre = reorder(main_genre, -rating, FUN = mean))

ggplot(allmovies_q1, aes(main_genre, y = rating)) +
  geom_boxplot(fill = "skyblue", color = "black") +
  stat_summary(fun = mean, geom = "point", color = "red", size = 1) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(title = "IMDB Rating by Genre (2000 - 2023)", x = "Genre", y = "IMDB Rating")

ggsave("Q1_Genre_vs_Rating_boxplot.png")

# Show basic descriptive stats by genre.
aggregate(rating ~ main_genre, allmovies_q1, mean)
aggregate(rating ~ main_genre, allmovies_q1, sd)

mean_table <- aggregate(rating ~ main_genre, allmovies_q1, mean)
mean_table <- mean_table[order(-mean_table$rating), ]
mean_table

library(gridExtra)
library(grid)

table_plot <- tableGrob(mean_table)
png("Q1_Mean_Rating_Table.png", width = 800, height = 600)
grid.draw(table_plot)
dev.off()
```

```{r, echo=T}
# Step 5) ANOVA + Tukey post-hoc
# Test if mean ratings differ across genres (ANOVA + Tukey).
anova_result <- aov(rating ~ main_genre, data = allmovies_q1)
summary(anova_result)

library(dplyr)
library(ggplot2)

summary_table <- allmovies_q1 %>%
  group_by(main_genre) %>%
  summarize(
    mean_rating = mean(rating),
    se = sd(rating)/sqrt(n()),
    .groups = "drop"
  )

p_anova <- ggplot(summary_table,
                  aes(x = reorder(main_genre, -mean_rating),
                      y = mean_rating)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = mean_rating - 1.96*se,
                    ymax = mean_rating + 1.96*se),
                width = 0.2) +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Mean IMDB Rating with 95% CI (2000–2023)",
       x = "Genre",
       y = "Mean Rating")

ggsave("Q1_ANOVA_Mean_CI.png", p_anova, width = 11, height = 6, dpi = 300)

tukey <- TukeyHSD(anova_result)
tukey

# install.packages(c("multcompView", "dplyr", "ggplot2"))

library(multcompView)
library(dplyr)
library(ggplot2)

allmovies_q1$main_genre <- as.factor(gsub("-", "_", as.character(allmovies_q1$main_genre)))

anova_result <- aov(rating ~ main_genre, data = allmovies_q1)
tukey <- TukeyHSD(anova_result)

letters <- multcompLetters4(anova_result, tukey)

mean_table <- allmovies_q1 %>%
  group_by(main_genre) %>%
  summarize(mean_rating = mean(rating), .groups = "drop") %>%
  mutate(letter = letters$main_genre[as.character(main_genre)]) %>%
  arrange(desc(mean_rating))

p_letters <- ggplot(mean_table, aes(x = reorder(main_genre, -mean_rating), y = mean_rating)) +
  geom_col(fill = "lavender", color = "black") +
  geom_text(aes(label = letter), vjust = -0.4, size = 4) +
  theme_minimal(base_size = 12) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Mean IMDB Rating by Genre with Tukey Grouping (2000–2023)",
       x = "Genre", y = "Mean IMDB Rating")

ggsave("Q1_Tukey_Grouping_Letters.png", p_letters, width = 11, height = 6, dpi = 300)

# ANOVA result: one-way ANOVA was tested to compare mean IMDB ratings across 17 main genres. The result was statistically significant, F(16, 74981) = 469, p < 0.001, indicating that at least one genre has a different mean rating. Due to large sample size, relatively small differences may become statistically significant.

# Tukey Post-hoc result: with further analysis, sport has significantly higher mean ratings than most other genres, horror has significantly lower mean ratings than nearly all genres. Biography and History are no significantly different from each other, indicating they belong to a similar rating group. 

# Overall, genre has a statistically meaningful effect on IMDB ratings.
```
```{r, echo=T}
plot(tukey)
```