---
title: "Project 1 Action vs History Runtime"
author: "Chris Karpovich"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 
```


```{r, echo=T}
#Importing Necessary Libraries
library(ezids)
library(ggplot2)

#Importing each .csv as data frames, grouped by genre
action = read.csv("action.csv")  
adventure = read.csv("adventure.csv")
animation = read.csv("animation.csv")
biography = read.csv("biography.csv")
crime = read.csv("crime.csv")
family = read.csv("family.csv")
fantasy = read.csv("fantasy.csv")
noir = read.csv("film-noir.csv")
history = read.csv("history.csv")
horror = read.csv("horror.csv")
mystery = read.csv("mystery.csv")
romance = read.csv("romance.csv")
scifi = read.csv("scifi.csv")
sports = read.csv("sports.csv")
thriller = read.csv("thriller.csv")
war = read.csv("war.csv")
```

```{r, echo=T}
#Checking structure of the data frames (all should be the same as action)
str(action)
```
```{r, echo=T}
#We can remove some columns as we will not be needing them (some others are left in as we could use possibly ask more questions about them later)
action = subset(action, select = -c(description, director, director_id, star, star_id, gross.in...))

#Showing the new structure of the data frame
str(action)
```
```{r, echo=T}
#Removing the columns for the rest of the data frames
adventure = subset(adventure, select = -c(description, director, director_id, star, star_id, gross.in...))

animation = subset(animation, select = -c(description, director, director_id, star, star_id, gross.in...))

biography = subset(biography, select = -c(description, director, director_id, star, star_id, gross.in...))

crime = subset(crime, select = -c(description, director, director_id, star, star_id, gross.in...))

family = subset(family, select = -c(description, director, director_id, star, star_id, gross.in...))

fantasy = subset(fantasy, select = -c(description, director, director_id, star, star_id, gross.in...))

noir = subset(noir, select = -c(description, director, director_id, star, star_id, gross.in...))

history = subset(history, select = -c(description, director, director_id, star, star_id, gross.in...))

horror = subset(horror, select = -c(description, director, director_id, star, star_id, gross.in...))

mystery = subset(mystery, select = -c(description, director, director_id, star, star_id, gross.in...))

romance = subset(romance, select = -c(description, director, director_id, star, star_id, gross.in...))

scifi = subset(scifi, select = -c(description, director, director_id, star, star_id, gross.in...))

sports = subset(sports, select = -c(description, director, director_id, star, star_id, gross.in...))

thriller = subset(thriller, select = -c(description, director, director_id, star, star_id, gross.in...))

war = subset(war, select = -c(description, director, director_id, star, star_id, gross.in...))
```

```{r, echo=T}

#Data Cleaning

allmovies = rbind(action, adventure, animation, biography, crime, family, fantasy, noir, history, horror, mystery, romance, scifi, sports, thriller, war)

allmovies$year = as.numeric(allmovies$year)
allmovies$runtime = as.numeric(gsub(" min", "", allmovies$runtime))

allmovies = subset(allmovies, year >=2000)

#Remove duplicates
allmovies = allmovies[!duplicated(allmovies$movie_id), ]

#Check for duplicates
duplicates = sum(duplicated(allmovies$movie_id))
duplicates

#Remove NA values from runtime
allmovies = subset(allmovies, is.na(runtime) == FALSE)

str(allmovies)
```
```{r, echo=T}
pre2010 = subset(allmovies, year < 2010)
pre2010 = subset(pre2010, runtime >=30)
pre2010 = subset(pre2010, runtime <=240)

post2010 = subset(allmovies, year >=2010)
post2010 = subset(post2010, runtime >=30)
post2010 = subset(post2010, runtime <=240)

str(pre2010)
str(post2010)
```

```{r, echo=T}
ggplot(data=pre2010, aes(x=runtime)) + 
  geom_histogram(col="yellow", 
                 fill="darkblue", 
                 alpha = .7) +
  labs(x="Runtime", y="Frequency") +
  labs(title="Distribution of Runtimes for Movies Produced Before 2010") 


ggplot(data=post2010, aes(x=runtime)) + 
  geom_histogram(col="red", 
                 fill="black", 
                 alpha = .7) +
  labs(x="Runtime", y="Frequency") +
  labs(title="Distribution of Runtimes for for Movies Produced After 2010") 

summary(pre2010$runtime)
summary(post2010$runtime)
```

```{r, echo=T}
#combining into 1 Data frame to produce boxplots
pre2010$timeframe = "Pre 2010"
post2010$timeframe = "Post 2010"

yeartest=rbind(pre2010, post2010)


ggplot(yeartest, aes(x=timeframe, y=runtime)) + 
  geom_boxplot( color ="blue",fill = "yellow", outlier.color="red", outlier.shape=8, outlier.size=4) +
  labs(title="Boxplot of Runtime for Movies Before and After 2010", x="Genre", y = "Runtime")

```

```{r, echo=T}
ttestyear = t.test(pre2010$runtime, post2010$runtime)
ttestyear

```