---
title: "Project 1 EDA"
author: "Team 1"
output:
  html_document:
    code_folding: show
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 
```


```{r, echo=T}
#Importing Necessary Libraries
library(ezids)
library(ggplot2)

#Importing each .csv as data frames, grouped by genre
action = read.csv("action.csv")  
adventure = read.csv("adventure.csv")
animation = read.csv("animation.csv")
biography = read.csv("biography.csv")
crime = read.csv("crime.csv")
family = read.csv("family.csv")
fantasy = read.csv("fantasy.csv")
noir = read.csv("film-noir.csv")
history = read.csv("history.csv")
horror = read.csv("horror.csv")
mystery = read.csv("mystery.csv")
romance = read.csv("romance.csv")
scifi = read.csv("scifi.csv")
sports = read.csv("sports.csv")
thriller = read.csv("thriller.csv")
war = read.csv("war.csv")
```

```{r, echo=T}
#Checking structure of the data frames (all should be the same as action)
str(action)
```
```{r, echo=T}
#We can remove some columns as we will not be needing them (some others are left in as we could use possibly ask more questions about them later)
action = subset(action, select = -c(description, director, director_id, star, star_id, gross.in...))

#Showing the new structire of the data frame
str(action)
```
```{r, echo=T}
#Removing the columns for the rest of the data frames
adventure = subset(adventure, select = -c(description, director, director_id, star, star_id, gross.in...))

animation = subset(animation, select = -c(description, director, director_id, star, star_id, gross.in...))

biography = subset(biography, select = -c(description, director, director_id, star, star_id, gross.in...))

crime = subset(crime, select = -c(description, director, director_id, star, star_id, gross.in...))

family = subset(family, select = -c(description, director, director_id, star, star_id, gross.in...))

fantasy = subset(fantasy, select = -c(description, director, director_id, star, star_id, gross.in...))

noir = subset(noir, select = -c(description, director, director_id, star, star_id, gross.in...))

history = subset(history, select = -c(description, director, director_id, star, star_id, gross.in...))

horror = subset(horror, select = -c(description, director, director_id, star, star_id, gross.in...))

mystery = subset(mystery, select = -c(description, director, director_id, star, star_id, gross.in...))

romance = subset(romance, select = -c(description, director, director_id, star, star_id, gross.in...))

scifi = subset(scifi, select = -c(description, director, director_id, star, star_id, gross.in...))

sports = subset(sports, select = -c(description, director, director_id, star, star_id, gross.in...))

thriller = subset(thriller, select = -c(description, director, director_id, star, star_id, gross.in...))

war = subset(war, select = -c(description, director, director_id, star, star_id, gross.in...))
```

```{r, echo=T}
#Combining all the data frames and removing duplicates, we can still use the data frames above for analysis, however.  Both methods are valid depending on our questions and eda.
allmovies = rbind(action, adventure, animation, biography, crime, family, fantasy, noir, history, horror, mystery, romance, scifi, sports, thriller, war)

#Remove duplicates
allmovies = allmovies[!duplicated(allmovies$movie_id), ]

#Check for duplicates
duplicates = sum(duplicated(allmovies))
duplicates

#Make year numeric
allmovies$year = as.numeric(allmovies$year)

#Create a filter for past 20 years and remove movies with no rating
recentmovies= subset(allmovies, year >= 2000)
recentmovies= subset(recentmovies, year <= 2023)
recentmovies = recentmovies[!is.na(recentmovies$rating), ]

summary(recentmovies$year)
```

```{r, echo=T}
#Splitting up each genre (NOTE: Film-Noir is not included because there are no movies made after 2000 in that genre)
action2 = recentmovies[grep("Action", recentmovies$genre), ]
action2$genre = "Action"

adventure2 = recentmovies[grep("Adventure", recentmovies$genre), ]
adventure2$genre = "Adventure"

animation2 = recentmovies[grep("Animation", recentmovies$genre), ]
animation2$genre = "Animation"

biography2 = recentmovies[grep("Biography", recentmovies$genre), ]
biography2$genre = "Biography"

crime2 = recentmovies[grep("Crime", recentmovies$genre), ]
crime2$genre = "Crime"

family2 = recentmovies[grep("Family", recentmovies$genre), ]
family2$genre = "Family"

fantasy2 = recentmovies[grep("Fantasy", recentmovies$genre), ]
fantasy2$genre = "Fantasy"


history2 = recentmovies[grep("History", recentmovies$genre), ]
history2$genre = "History"

horror2 = recentmovies[grep("Horror", recentmovies$genre), ]
horror2$genre = "Horror"

mystery2 = recentmovies[grep("Mystery", recentmovies$genre), ]
mystery2$genre = "Mystery"

romance2 = recentmovies[grep("Romance", recentmovies$genre), ]
romance2$genre = "Romance"

scifi2 = recentmovies[grep("Sci-Fi", recentmovies$genre), ]
scifi2$genre = "Sci-Fi"

sports2 = recentmovies[grep("Sport", recentmovies$genre), ]
sports2$genre = "Sports"

thriller2 = recentmovies[grep("Thriller", recentmovies$genre), ]
thriller2$genre = "Thriller"

war2 = recentmovies[grep("War", recentmovies$genre), ]
war2$genre = "War"

#Adding the new genre data frames to a final data frame

fullmovielist = rbind(action2, adventure2, animation2, biography2, crime2, family2, fantasy2, history2, horror2, mystery2, romance2, scifi2, sports2, thriller2, war2)

str(fullmovielist)

```

```{r, echo=T}
nrow(recentmovies)      
nrow(fullmovielist)      
length(unique(fullmovielist$movie_id))  


unique(fullmovielist$genre)

table(fullmovielist$genre)

```

```{r, echo=T}
#Contingency Table Movies by Year and Genre
movietable = table(fullmovielist$year, fullmovielist$genre)

movietable
```

```{r, echo=T}
#Chi-Square Test
chisqtest = chisq.test(movietable)
chisqtest
```

```{r, echo=T}
#Checking Histogram to determine the frequencies

ggplot(data=fullmovielist, aes(year)) + 
  geom_histogram(binwidth=1,
                 col="red", 
                 fill="blue", 
                 alpha = .7) +
labs(x='Year', y='Number of Movies', title = "Movie Production By Genre")

#I'll need to work with ratios rather than raw numbers, the amount of movies increases so much over time it is effecting the test
```

```{r, echo=T}
moviesperyear = rowSums(movietable)
moviesperyear
```